### ISSUE TITLE
serialport library update necessary

### ISSUE THREAD

**Issue by Klaus5555** [soef/ioBroker.wm-bus#30]
Is there someone who can take care of the problem with the serialport library.

---

**System data:**

Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v12.18.2
NPM: 6.14.5
JS-Controller (1): 3.1.6
Admin: 4.1.6
Wireless M-Bus: 0.3.1

> *created by ioBroker.info*

**Comment by f2daz** [comment]
Would be great, if the adapter could be maintained again. I just tried the forks, but unfortunately the have all the same problem with the serialport library -.-

**Comment by stevie77** [comment]
Is this adapter dead in general because of this serialport problem? I even cannot install it. Is this the same problem? Can you still use it or does this problem disable the adapter until it is fixed (for people already having installed it)?

`In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:409:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterDrain(uv_work_t*)’:../src/serialport.cpp:424:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(1, argv);                              ^In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~../src/serialport.cpp: At global scope:../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses] SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {                            ^../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses] SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {                              ^../src/serialport.cpp:460:17: error: variable or field ‘init’ declared void   void init(v8::Handle<v8::Object> target) {                 ^~~~~~../src/serialport.cpp:460:17: error: ‘Handle’ is not a member of ‘v8’../src/serialport.cpp:460:34: error: expected primary-expression before ‘>’ token   void init(v8::Handle<v8::Object> target) {                                  ^../src/serialport.cpp:460:36: error: ‘target’ was not declared in this scope   void init(v8::Handle<v8::Object> target) {
                                    ^~~~~~
../src/serialport.cpp:460:36: note: suggested alternative: ‘tzset’   void init(v8::Handle<v8::Object> target) {                                    ^~~~~~                                    tzsetIn file included from ../../../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../src/serialport.cpp:485:25: error: ‘init’ was not declared in this scope NODE_MODULE(serialport, init);                         ^~~~/opt/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:736:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../src/serialport.cpp:485:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(serialport, init); ^~~~~~~~~~~
../src/serialport.cpp:485:25: note: suggested alternative: ‘int’ NODE_MODULE(serialport, init);                         ^~~~/opt/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:736:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../src/serialport.cpp:485:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(serialport, init); ^~~~~~~~~~~
make: *** [serialport.target.mk:112: Release/obj.target/serialport/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack     at ChildProcess.emit (events.js:314:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.83-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/iobroker.wm-bus/node_modules/serialportgyp ERR! node -v v12.22.1gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1npm ERR! npm ERR! Failed at the serialport@6.2.2 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
